USE [master]
GO
/****** Object:  Database [Howzit]    Script Date: 6/29/2020 2:22:08 PM ******/
CREATE DATABASE [Howzit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Howzit', FILENAME = N'E:\Term 8\project\Howzit\Howzit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Howzit_log', FILENAME = N'E:\Term 8\project\Howzit\Howzit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Howzit] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Howzit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Howzit] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Howzit] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Howzit] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Howzit] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Howzit] SET ARITHABORT OFF 
GO
ALTER DATABASE [Howzit] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Howzit] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Howzit] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Howzit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Howzit] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Howzit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Howzit] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Howzit] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Howzit] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Howzit] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Howzit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Howzit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Howzit] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Howzit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Howzit] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Howzit] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Howzit] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Howzit] SET RECOVERY FULL 
GO
ALTER DATABASE [Howzit] SET  MULTI_USER 
GO
ALTER DATABASE [Howzit] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Howzit] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Howzit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Howzit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Howzit] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Howzit', N'ON'
GO
ALTER DATABASE [Howzit] SET QUERY_STORE = OFF
GO
USE [Howzit]
GO
/****** Object:  Table [dbo].[chat]    Script Date: 6/29/2020 2:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[chat](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[delete_time] [time](7) NULL,
	[user_id] [int] NULL,
 CONSTRAINT [PK_chat] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[chat_memeber]    Script Date: 6/29/2020 2:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[chat_memeber](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NULL,
	[chat_id] [int] NULL,
 CONSTRAINT [PK_chat_memeber] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[contact]    Script Date: 6/29/2020 2:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[contact](
	[contact_ID] [int] IDENTITY(1,1) NOT NULL,
	[contact_name] [nvarchar](50) NOT NULL,
	[user_id] [int] NULL,
 CONSTRAINT [PK_contact] PRIMARY KEY CLUSTERED 
(
	[contact_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Document]    Script Date: 6/29/2020 2:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Document](
	[document_ID] [int] IDENTITY(1,1) NOT NULL,
	[file_name] [nvarchar](50) NOT NULL,
	[file_size] [int] NOT NULL,
	[message_id] [int] NULL,
 CONSTRAINT [PK_Document] PRIMARY KEY CLUSTERED 
(
	[document_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[message]    Script Date: 6/29/2020 2:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[message](
	[message_ID] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime] NOT NULL,
	[text] [ntext] NULL,
	[is_edited] [bit] NOT NULL,
	[is_seen] [bit] NOT NULL,
	[chat_id] [int] NULL,
	[doc_id] [int] NULL,
 CONSTRAINT [PK_message] PRIMARY KEY CLUSTERED 
(
	[message_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 6/29/2020 2:22:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[phone_IP] [nvarchar](50) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[chat]  WITH CHECK ADD  CONSTRAINT [FK_chat_User] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[chat] CHECK CONSTRAINT [FK_chat_User]
GO
ALTER TABLE [dbo].[chat_memeber]  WITH CHECK ADD  CONSTRAINT [FK_chat_memeber_chat] FOREIGN KEY([user_id])
REFERENCES [dbo].[chat] ([ID])
GO
ALTER TABLE [dbo].[chat_memeber] CHECK CONSTRAINT [FK_chat_memeber_chat]
GO
ALTER TABLE [dbo].[chat_memeber]  WITH CHECK ADD  CONSTRAINT [FK_chat_memeber_User] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[chat_memeber] CHECK CONSTRAINT [FK_chat_memeber_User]
GO
ALTER TABLE [dbo].[contact]  WITH CHECK ADD  CONSTRAINT [FK_contact_User] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[contact] CHECK CONSTRAINT [FK_contact_User]
GO
ALTER TABLE [dbo].[Document]  WITH CHECK ADD  CONSTRAINT [FK_Document_message] FOREIGN KEY([message_id])
REFERENCES [dbo].[message] ([message_ID])
GO
ALTER TABLE [dbo].[Document] CHECK CONSTRAINT [FK_Document_message]
GO
ALTER TABLE [dbo].[message]  WITH CHECK ADD  CONSTRAINT [FK_message_chat] FOREIGN KEY([chat_id])
REFERENCES [dbo].[chat] ([ID])
GO
ALTER TABLE [dbo].[message] CHECK CONSTRAINT [FK_message_chat]
GO
USE [master]
GO
ALTER DATABASE [Howzit] SET  READ_WRITE 
GO
